### PR TITLE
flip animation with both directions

### PR DESCRIPTION
**Pull request by martinposchmann**

### CODE REVIEW

**Comment by xenione** [comment]
Before all thanks for your collaborations. Could you use any pattern as strategy pattern otherwise is all fill full with "ifs"

**Comment by m1ndlab** [comment]
Yes, a strategy pattern would probably be more elegant. I'll do some rewriting in the next couple of days.

**Comment by martinposchmann** [comment]
Yes, a strategy pattern would probably be more elegant. I'll do some rewriting within the next couple of days.

**Comment by martinposchmann** [comment]
The animation code now resides in its own classes, using an abstract base class. Hopefully its not too much of a change.

**Comment by xenione** [comment]
Good job!!!. Could you update readme?

**Pull request merged**
